"""RCA Post-Mortem Markdown Generator adhering to strict production schema."""

from typing import List, Optional, Dict, Any
from pydantic import BaseModel


class RCAPostMortem(BaseModel):
    incident_id: str
    service_name: str
    summary: str
    root_cause: str
    evidence: str
    validation_output: str
    preventative_actions: List[str]
    markdown_report: str


class RCAFormatter:
    """Formats incident post-mortems according to the strict Zero-Noise SRE specification."""

    @staticmethod
    def format_rca(
        incident_id: str,
        service_name: str,
        summary: str,
        root_cause: str,
        evidence: str,
        validation_output: str,
        preventative_actions: Optional[List[str]] = None,
        patch_diff: Optional[str] = None
    ) -> RCAPostMortem:
        actions = preventative_actions or [
            "Add automated schema validation at ingestion boundaries.",
            "Expand regression test suites to cover nullable telemetry fields."
        ]
        actions_md = "\n".join(f"- {act}" for act in actions)

        diff_section = ""
        if patch_diff:
            diff_section = f"""
### Synthesized Patch Diff
```diff
{patch_diff}
```
"""

        md = f"""# Incident Root Cause Analysis (RCA) Post-Mortem

**Incident ID:** `{incident_id}`  
**Impacted Service:** `{service_name}`  
**Status:** `RESOLVED & VERIFIED IN SANDBOX`  
**Generated By:** `Zero-Noise SRE Core (Gemma-Agent)`

---

## 1. Summary
{summary}

## 2. Root Cause
{root_cause}

## 3. Evidence
{evidence}

## 4. Sandbox Validation Output
```text
{validation_output.strip()}
```
{diff_section}
## 5. Preventative & Follow-up Actions
{actions_md}

---
*Autonomous Post-Mortem automatically dispatched with Pull Request.*
"""
        return RCAPostMortem(
            incident_id=incident_id,
            service_name=service_name,
            summary=summary,
            root_cause=root_cause,
            evidence=evidence,
            validation_output=validation_output,
            preventative_actions=actions,
            markdown_report=md
        )
