version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.55
    container_name: sre-jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686" # Web UI
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    networks:
      - sre-network

  prometheus:
    image: prom/prometheus:v2.50.1
    container_name: sre-prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=2h
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - sre-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.96.0
    container_name: sre-otel-collector
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    volumes:
      - ./config/otel-collector.yaml:/etc/otelcol-contrib/config.yaml:ro
    ports:
      - "8889:8889"   # Prometheus metrics exporter
    depends_on:
      - jaeger
    networks:
      - sre-network

networks:
  sre-network:
    driver: bridge
