"""SRE Coordinator implementing the full 4-stage autonomous triage state machine."""

import os
from typing import Dict, Any, Optional, List
from pydantic import BaseModel, Field

from ..ingestion.anomaly_detector import IncidentPayload
from ..topology.graph_builder import TopologyGraphBuilder
from ..topology.causal_tracer import CausalTracer, CausalPathResult
from ..topology.context_distiller import ContextDistiller, CompressedContext
from .prompt_templates import SRE_PROMPT_TEMPLATE, GEMMA_INSTRUCT_WRAPPER
from .llm_client import LLMClient
from .tools.git_tools import GitTools
from .tools.metrics_tools import MetricsTools
from .tools.trace_tools import TraceTools
from ..sandbox.docker_runner import SandboxRunner
from ..sandbox.test_validator import TestValidator, TestValidationSummary
from ..remediation.patch_generator import PatchGenerator, UnifiedPatch
from ..remediation.pr_issuer import PRIssuer, PRResult
from ..remediation.rca_formatter import RCAFormatter, RCAPostMortem


class TriageState(BaseModel):
    incident: IncidentPayload
    stage: str = "INITIALIZED"
    causal_result: Optional[CausalPathResult] = None
    compressed_context: Optional[CompressedContext] = None
    llm_hypothesis: Optional[str] = None
    synthesized_patch: Optional[str] = None
    reproduction_test: Optional[str] = None
    target_file: Optional[str] = None
    validation_summary: Optional[TestValidationSummary] = None
    unified_patch: Optional[UnifiedPatch] = None
    rca: Optional[RCAPostMortem] = None
    pr_result: Optional[PRResult] = None
    logs: List[str] = Field(default_factory=list)


class SRECoordinator:
    """State-machine coordinator for Zero-Noise SRE Core."""

    def __init__(
        self,
        llm_client: LLMClient,
        git_tools: Optional[GitTools] = None,
        metrics_tools: Optional[MetricsTools] = None,
        trace_tools: Optional[TraceTools] = None,
        sandbox_runner: Optional[SandboxRunner] = None,
        pr_issuer: Optional[PRIssuer] = None,
        service_repo_base: str = "tests/fixtures"
    ):
        self.llm_client = llm_client
        self.git_tools = git_tools or GitTools(service_repo_base)
        self.metrics_tools = metrics_tools or MetricsTools()
        self.trace_tools = trace_tools or TraceTools()
        self.sandbox_runner = sandbox_runner or SandboxRunner()
        self.test_validator = TestValidator(self.sandbox_runner)
        self.pr_issuer = pr_issuer or PRIssuer()
        self.service_repo_base = service_repo_base

    async def execute_triage(self, incident: IncidentPayload) -> TriageState:
        state = TriageState(incident=incident)
        state.logs.append(f"[INIT] Started automated triage for {incident.incident_id} on {incident.service_name}")

        # STAGE 1: Symptom & Topology Isolation
        state.stage = "STAGE_1_TOPOLOGY_ISOLATION"
        state.logs.append("[STAGE 1] Building topology DAG and isolating culprit span...")
        graph_builder = TopologyGraphBuilder()
        graph_builder.build_from_spans(incident.sample_spans)
        tracer = CausalTracer(graph_builder.graph)
        causal_result = tracer.trace_root_cause(incident.sample_spans)
        state.causal_result = causal_result
        state.logs.append(f"[STAGE 1] Isolated culprit: {causal_result.culprit_service}:{causal_result.culprit_operation}")

        # STAGE 2: Causal Correlation
        state.stage = "STAGE_2_CAUSAL_CORRELATION"
        state.logs.append("[STAGE 2] Fetching git diffs and distilling high-signal context for Gemma...")
        git_diff_res = self.git_tools.get_service_git_diff(causal_result.culprit_service)
        compressed_ctx = ContextDistiller.distill(
            causal_result=causal_result,
            spans=incident.sample_spans,
            recent_git_diff=git_diff_res.unified_diff
        )
        state.compressed_context = compressed_ctx
        state.logs.append("[STAGE 2] Telemetry successfully distilled into compact prompt block.")

        # STAGE 3: Sandboxed Reproduction & Fix Synthesis
        state.stage = "STAGE_3_SANDBOX_SYNTHESIS"
        state.logs.append("[STAGE 3] Prompting Gemma agent to synthesize patch and reproduction test...")
        prompt = SRE_PROMPT_TEMPLATE.format(incident_context=compressed_ctx.compact_prompt_block)
        formatted_prompt = GEMMA_INSTRUCT_WRAPPER.format(prompt=prompt)

        llm_resp = await self.llm_client.generate(formatted_prompt)
        parsed = llm_resp.parsed_json or {}

        state.llm_hypothesis = parsed.get("hypothesis", "Hypothesis generated by SRE Core")
        state.target_file = parsed.get("target_file", "app.py")
        state.synthesized_patch = parsed.get("patch_code", "")
        state.reproduction_test = parsed.get("reproduction_test_code", "")
        state.logs.append(f"[HYPOTHESIS] {state.llm_hypothesis}")

        # Validate in Ephemeral Sandbox
        state.logs.append("[SANDBOX] Running verification loop in ephemeral sandbox...")
        service_dir = os.path.join(self.service_repo_base, causal_result.culprit_service)
        val_summary = self.test_validator.validate_patch(
            service_dir=service_dir,
            target_file=state.target_file,
            patch_code=state.synthesized_patch,
            reproduction_test_code=state.reproduction_test
        )
        state.validation_summary = val_summary
        state.logs.append(f"[VALIDATION] {val_summary.summary}")

        # Generate Unified Patch Diff
        orig_content = ""
        orig_file_path = os.path.join(service_dir, state.target_file)
        if os.path.exists(orig_file_path):
            with open(orig_file_path, "r", encoding="utf-8") as f:
                orig_content = f.read()
        state.unified_patch = PatchGenerator.generate_diff(
            target_file=state.target_file,
            original_content=orig_content,
            patched_content=state.synthesized_patch
        )

        # STAGE 4: Pull Request & RCA Generation
        state.stage = "STAGE_4_PR_AND_RCA"
        state.logs.append("[STAGE 4] Formatting Markdown Post-Mortem and dispatching Pull Request...")
        rca_data = parsed.get("rca", {})
        rca_post_mortem = RCAFormatter.format_rca(
            incident_id=incident.incident_id,
            service_name=incident.service_name,
            summary=rca_data.get("summary", f"Incident {incident.incident_id} triggered by {incident.trigger_reason}"),
            root_cause=rca_data.get("root_cause", causal_result.root_cause_summary),
            evidence=rca_data.get("evidence", f"Observed p99: {incident.observed_p99_ms:.2f}ms, Error Rate: {incident.observed_error_rate_pct:.2f}%"),
            validation_output=val_summary.details.stdout or "All reproduction and regression unit tests passed.",
            preventative_actions=rca_data.get("preventative_actions"),
            patch_diff=state.unified_patch.diff_text
        )
        state.rca = rca_post_mortem

        pr_result = self.pr_issuer.publish_github_pr(
            repo_dir=service_dir,
            service_name=causal_result.culprit_service,
            incident_id=incident.incident_id,
            target_file=state.target_file,
            patch_content=state.synthesized_patch,
            test_file="test_reproduction.py",
            test_content=state.reproduction_test,
            rca_markdown=rca_post_mortem.markdown_report
        )
        state.pr_result = pr_result
        state.stage = "RESOLVED"
        state.logs.append(f"[DISPATCH] Pull Request opened successfully: {pr_result.pr_url}")

        return state
